"""Tests for dealradar.models — the data contracts. See tests/conftest.py for the shared fixtures."""

from __future__ import annotations

from datetime import datetime, timezone

import pytest
from pydantic import ValidationError

from dealradar.models import Offer, QualityScore, RunReport, Watch, validate_gtin

NOW = datetime(2026, 8, 9, 12, 0, 0, tzinfo=timezone.utc)


# --------------------------------------------------------------------------------------------------
# validate_gtin — independently-sourced real EAN-13 / EAN-8 codes, not generated by our own function.
# --------------------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "code",
    [
        "4006381333931",  # EAN-13
        "5901234123457",  # EAN-13
        "3017620422003",  # EAN-13
        "40170725",  # EAN-8
        "73513537",  # EAN-8
        "96385074",  # EAN-8
    ],
)
def test_validate_gtin_accepts_known_valid_codes(code: str) -> None:
    assert validate_gtin(code) is True


@pytest.mark.parametrize(
    "code",
    [
        "4006381333932",  # valid code with last digit flipped
        "40170726",  # valid EAN-8 with last digit flipped
        "123456789",  # wrong length (9)
        "12345",  # wrong length (5)
        "4006381A33931",  # non-digit character
        "",  # empty
    ],
)
def test_validate_gtin_rejects_invalid_codes(code: str) -> None:
    assert validate_gtin(code) is False


def test_validate_gtin_rejects_non_string() -> None:
    assert validate_gtin(4006381333931) is False  # type: ignore[arg-type]


# --------------------------------------------------------------------------------------------------
# Grosze — floats must be rejected, not silently truncated/converted
# --------------------------------------------------------------------------------------------------


def _base_offer_kwargs() -> dict[str, object]:
    return dict(
        source_id=1,
        external_id="ext-1",
        first_seen=NOW,
        last_seen=NOW,
        title="Test product",
        url="https://example.test/product",
        price_gross=10000,
    )


def test_offer_accepts_int_price() -> None:
    offer = Offer(**_base_offer_kwargs())  # type: ignore[arg-type]
    assert offer.price_gross == 10000


def test_offer_rejects_float_price_gross() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["price_gross"] = 100.0
    with pytest.raises(ValidationError):
        Offer(**kwargs)  # type: ignore[arg-type]


def test_offer_rejects_float_shipping_cost() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["shipping_cost"] = 9.99
    with pytest.raises(ValidationError):
        Offer(**kwargs)  # type: ignore[arg-type]


# --------------------------------------------------------------------------------------------------
# Offer.price_total / price_incomplete — computed, not accepted
# --------------------------------------------------------------------------------------------------


def test_price_total_sums_gross_and_shipping() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["price_gross"] = 10000
    kwargs["shipping_cost"] = 1500
    offer = Offer(**kwargs)  # type: ignore[arg-type]
    assert offer.price_total == 11500
    assert offer.price_incomplete is False


def test_price_incomplete_when_shipping_unknown() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["price_gross"] = 10000
    kwargs["shipping_cost"] = None
    offer = Offer(**kwargs)  # type: ignore[arg-type]
    assert offer.price_total == 10000  # missing shipping treated as 0 for the sum, but flagged incomplete
    assert offer.price_incomplete is True


def test_price_total_is_not_an_accepted_constructor_argument() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["price_total"] = 999999  # must be rejected: computed, not accepted (extra="forbid")
    with pytest.raises(ValidationError):
        Offer(**kwargs)  # type: ignore[arg-type]


# --------------------------------------------------------------------------------------------------
# Offer.ean — invalid EAN is dropped to None with a reason, never silently kept
# --------------------------------------------------------------------------------------------------


def test_invalid_ean_becomes_none_with_reason() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["ean"] = "4006381333932"  # valid EAN with the check digit flipped
    offer = Offer(**kwargs)  # type: ignore[arg-type]
    assert offer.ean is None
    assert any("4006381333932" in issue for issue in offer.data_issues)


def test_valid_ean_is_preserved() -> None:
    kwargs = _base_offer_kwargs()
    kwargs["ean"] = "4006381333931"
    offer = Offer(**kwargs)  # type: ignore[arg-type]
    assert offer.ean == "4006381333931"
    assert offer.data_issues == []


def test_missing_ean_is_none_without_issue() -> None:
    offer = Offer(**_base_offer_kwargs())  # type: ignore[arg-type]
    assert offer.ean is None
    assert offer.data_issues == []


# --------------------------------------------------------------------------------------------------
# Z4 — absence needs a reason
# --------------------------------------------------------------------------------------------------


def test_quality_score_null_total_requires_missing_reason() -> None:
    with pytest.raises(ValidationError):
        QualityScore(product_id=1, computed_at=NOW, total_1_10=None)


def test_quality_score_null_total_with_reason_is_valid() -> None:
    qs = QualityScore(product_id=1, computed_at=NOW, total_1_10=None, missing_reason="no_utility_formula")
    assert qs.total_1_10 is None
    assert qs.missing_reason == "no_utility_formula"


def test_quality_score_with_value_needs_no_reason() -> None:
    qs = QualityScore(product_id=1, computed_at=NOW, total_1_10=7.4)
    assert qs.total_1_10 == 7.4


# --------------------------------------------------------------------------------------------------
# Watch — must target either a product or a query
# --------------------------------------------------------------------------------------------------


def test_watch_requires_product_id_or_query() -> None:
    with pytest.raises(ValidationError):
        Watch()


def test_watch_with_product_id_is_valid() -> None:
    w = Watch(product_id=42)
    assert w.channel == "console"


def test_watch_with_query_is_valid() -> None:
    w = Watch(query="ssd 2tb poniżej 400zł")
    assert w.product_id is None


# --------------------------------------------------------------------------------------------------
# RunReport
# --------------------------------------------------------------------------------------------------


def test_run_report_summary_line_contains_stage_and_status() -> None:
    report = RunReport(stage="collect", started_at=NOW, offers_fetched=12, sources_failed=["aliexpress"])
    line = report.summary_line()
    assert "collect" in line
    assert "aliexpress" in line
    assert "offers_fetched=12" in line
